---
# tasks file for php

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: php

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: php

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: php
