---
# tasks file for php (Ubuntu specific)

- name: Add PHP 5.5 PPA
  apt_repository: >
    repo='ppa:ondrej/php5'
    state=present
  when: php_version == 5.5
  tags: php

- name: Add PHP 5.6 PPA
  apt_repository: >
    repo='ppa:ondrej/php5-5.6'
    state=present
  when: php_version == 5.6
  tags: php

- name: Install PHP packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: php_packages
  tags: php
